# Generated by Django 5.0.2 on 2024-02-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_admin'),
        ('Guest', '0004_remove_tbl_newhospital_place_remove_tbl_user_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
