# Generated by Django 5.0 on 2024-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField(max_length=50)),
                ('available_formtime', models.CharField(max_length=50)),
                ('available_totime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(max_length=50)),
            ],
        ),
    ]
