# Generated by Django 5.0 on 2024-01-11 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0001_initial'),
        ('Hospital', '0002_alter_tbl_doctor_doctor_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_available',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_doctor'),
        ),
    ]
