# Generated by Django 5.0 on 2024-01-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0002_tbl_available_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_slots',
            name='available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultancy.tbl_available'),
        ),
        migrations.AddField(
            model_name='tbl_slots',
            name='slot_status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
