# Generated by Django 5.0.2 on 2024-02-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0004_rename_doctor_tbl_available_doctor'),
        ('User', '0013_remove_tbl_complaint_consultancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_slots',
            name='available',
        ),
        migrations.DeleteModel(
            name='tbl_available',
        ),
        migrations.DeleteModel(
            name='tbl_slots',
        ),
    ]
