# Generated by Django 5.0.2 on 2024-02-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consultancy', '0005_remove_tbl_slots_available_delete_tbl_available_and_more'),
        ('Hospital', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField(max_length=50)),
                ('available_formtime', models.CharField(max_length=50)),
                ('available_totime', models.CharField(max_length=50)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_doctor')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(max_length=50)),
                ('slot_status', models.CharField(default=0, max_length=2)),
                ('available', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultancy.tbl_available')),
            ],
        ),
    ]
