# Generated by Django 5.0 on 2024-01-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(upload_to='userdoc/'),
        ),
    ]
