# Generated by Django 5.0.2 on 2024-02-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newhospital',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
    ]
