# Generated by Django 5.0.2 on 2024-02-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_tbl_newhospital_place_remove_tbl_user_place'),
        ('Hospital', '0007_remove_tbl_doctor_department_and_more'),
        ('User', '0013_remove_tbl_complaint_consultancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newhospital',
            name='hospitaltype',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
        migrations.DeleteModel(
            name='tbl_newhospital',
        ),
    ]
