# Generated by Django 5.0.2 on 2024-02-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_initial'),
        ('Guest', '0005_remove_tbl_newhospital_hospitaltype_delete_tbl_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newhospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_email', models.CharField(max_length=50)),
                ('hospital_contact', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=50)),
                ('hospital_logo', models.FileField(upload_to='HosDoc/')),
                ('hospital_proof', models.FileField(upload_to='HosDOc/')),
                ('hospital_password', models.CharField(max_length=50)),
                ('hospital_vstatus', models.CharField(default=0, max_length=2)),
                ('hospitaltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_hospitaltype')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='userdoc/')),
                ('user_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
