# Generated by Django 5.0 on 2024-01-22 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_photo'),
        ('User', '0004_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhospital'),
        ),
    ]
