# Generated by Django 5.0 on 2024-01-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_tbl_consultancy_hospital_tbl_doctor_hospital'),
        ('User', '0007_tbl_feedback_hospital_alter_tbl_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='consultancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_consultancy'),
        ),
        migrations.AddField(
            model_name='tbl_feedback',
            name='consultancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_consultancy'),
        ),
    ]
