# Generated by Django 5.0 on 2024-01-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_complaint_consultancy_tbl_feedback_consultancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
