# Generated by Django 5.0 on 2024-01-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0004_rename_doctor_tbl_available_doctor'),
        ('Guest', '0003_alter_tbl_user_user_photo'),
        ('User', '0009_tbl_complaint_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('appointment_status', models.CharField(default=0, max_length=2)),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultancy.tbl_slots')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
