# Generated by Django 5.0.2 on 2024-02-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_remove_tbl_updatemedicine_appointment_and_more'),
        ('User', '0012_tbl_complaint_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='consultancy',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='consultancy',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_appointment',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
