# Generated by Django 5.0 on 2024-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_photo',
            field=models.FileField(upload_to='HosDoc/'),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='doctor_proof',
            field=models.FileField(upload_to='HosDoc/'),
        ),
    ]
