# Generated by Django 5.0 on 2024-01-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_photo'),
        ('Hospital', '0002_alter_tbl_doctor_doctor_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_consultancy',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhospital'),
        ),
        migrations.AddField(
            model_name='tbl_doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhospital'),
        ),
    ]
