# Generated by Django 5.0.2 on 2024-02-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
