# Generated by Django 5.0.2 on 2024-02-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultancy', '0005_remove_tbl_slots_available_delete_tbl_available_and_more'),
        ('Hospital', '0006_tbl_gallery'),
        ('User', '0013_remove_tbl_complaint_consultancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='tbl_consultancy',
        ),
        migrations.DeleteModel(
            name='tbl_doctor',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
