# Generated by Django 5.0 on 2024-01-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_updatemedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatemedicine_report', models.FileField(upload_to='HosDOc/')),
                ('updatemedicine_medical', models.CharField(max_length=50)),
                ('updatemedicine_major', models.CharField(max_length=50)),
            ],
        ),
    ]
