# Generated by Django 5.0 on 2024-02-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        ('User', '0010_tbl_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_updatemedicine',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_appointment'),
        ),
    ]
