# Generated by Django 5.0 on 2024-02-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_tbl_updatemedicine_appointment'),
        ('User', '0011_tbl_feedback_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_prescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribtion_medicine', models.CharField(max_length=50)),
                ('prescribtion_diet', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_appointment')),
            ],
        ),
    ]
