# Generated by Django 5.0 on 2024-02-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_tbl_prescribtion'),
        ('Guest', '0003_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_prescribtion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
