# Generated by Django 5.0 on 2024-02-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_tbl_prescribtion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_prescribtion',
            name='user',
        ),
    ]
