# Generated by Django 5.0.2 on 2024-02-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_remove_tbl_prescribtion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_updatemedicine',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='tbl_prescribtion',
        ),
        migrations.DeleteModel(
            name='tbl_updatemedicine',
        ),
    ]
