# Generated by Django 5.0.2 on 2024-02-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0006_remove_tbl_updatemedicine_appointment_and_more'),
        ('User', '0014_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_prescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribtion_medicine', models.CharField(max_length=50)),
                ('prescribtion_diet', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_appointment')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_updatemedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatemedicine_report', models.FileField(upload_to='HosDOc/')),
                ('updatemedicine_medical', models.CharField(max_length=50)),
                ('updatemedicine_major', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_appointment')),
            ],
        ),
    ]
